baseURL = 'https://ammar1c.github.io'
languageCode = 'en-us'
title = 'Ammar Al-Batool'
theme = "hello-friend-ng"


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Random thoughts about software engineering."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Blah blah blah"
  keywords = "Scala, blog, distributed systems, functional programming"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/ammar-al-batool-b85626132/"

[[params.social]]
  name = "github"
  url = "https://github.com/ammar1c"

[[params.social]]
  name = "twitter"
  url = "https://twitter.com/ammar_1c"

[languages]
  [languages.en]
    title = "Ammar Al-Batool"
    subtitle = "Human Android"
    keywords = "Distributed systems. Scala."
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Hello Internet"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"
