baseURL = 'https://ammar1c.github.io/'
languageCode = 'en-us'
title = 'Ammar'
theme = 'monday-theme'


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 3
